### ISSUE TITLE
Material Repo Todo

### ISSUE THREAD

**Issue by robi-y** [jce-il/se-class16b-prep#40]
- [x] update submission templates 
- [x] new exam repo with pointer to RTL editor!
- [x] move all assignments text from doc!
  - [ ] grade indicator 
  - [ ] sds: also server prototype
  - [ ] iterations: can assign different manager, can switch teams
    - [ ] Iteration end: documentation
  -       [ ] code review at class
    -[ ] separate typing mission
    -[ ] HW7
- [x] - Links from wiki technical -> webapp links
- [ ] - Links from wiki links -> modlule links
- [ ] remove warnings
- [x] RTL top main menu
- [ ] optional modules as Philip suggested
- [ ] current module marked
- [x] news page! maybe enough at wiki + chat update?
- [x] google analytics
- [x] google calendar + Machar

-[ ] icons for process and instruction?
Future:
- [ ] class quizzez, kahoot
